#!/bin/sh

set -eu

if [ "$#" != 0 ]; then
    echo "Usage: $0"
    exit 1
fi

password=${OPENAI_PASSWORD:-openai}

echo "Setting VNC and rewarder password: $password"
sudo -H -u xvnc vncpasswd >/dev/null <<EOF
$password
$password
EOF

mkdir -p /usr/local/openai/privileged_state
echo "$password" > /usr/local/openai/privileged_state/password
